services:
  ##### build images (cpu, cuda, rocm) #################################################################################
  cpu-build:
    build:
      context: .
      dockerfile: Dockerfile
      target: image
      args:
        src: cpu
    image: minimal-cpu
    profiles: [ "cpu", "pubsub", "yolo-cpu-torch", "yolo-cuda-torch", "yolo-rocm-torch" ]
  cpu-torch-build:
    build:
      context: .
      dockerfile: Dockerfile
      target: image
      args:
        src: cpu-torch
    image: minimal-cpu-torch
    profiles: [ "cpu-torch", "yolo-cpu-torch", "yolo-cpu-torch-test" ]
  cuda-torch-build:
    build:
      context: .
      dockerfile: Dockerfile
      target: image
      args:
        src: cuda-torch
    image: minimal-cuda-torch
    profiles: [ "cuda-torch", "yolo-cuda-torch" ]
  rocm-torch-build:
    build:
      context: .
      dockerfile: Dockerfile
      target: image
      args:
        src: rocm-torch
    image: minimal-rocm-torch
    profiles: [ "rocm-torch", "yolo-rocm-torch" ]
  ##### run pubsub examples (uses cpu version) #########################################################################
  sub:
    image: minimal-cpu:latest
    depends_on:
      - cpu-build
    container_name: sub
    volumes:
      - .:/src:ro
      - /etc/timezone:/etc/timezone:ro
    command: sh -c "mkdir -p "/build" && cd "/build" && cmake -DCMAKE_BUILD_TYPE=Release /src && cmake --build . --target sub  && src/pubsub/sub"
    stop_signal: SIGTERM
    network_mode: host
    ipc: host
    pid: host
    profiles: [ "pubsub" ]
  pub:
    image: minimal-cpu:latest
    depends_on:
      - cpu-build
    container_name: pub
    volumes:
      - .:/src:ro
      - /etc/timezone:/etc/timezone:ro
    command: sh -c "mkdir -p "/build" && cd "/build" && cmake -DCMAKE_BUILD_TYPE=Release /src && cmake --build . --target pub  && src/pubsub/pub"
    stop_signal: SIGTERM
    network_mode: host
    ipc: host
    pid: host
    profiles: [ "pubsub" ]
  python_sub:
    image: minimal-cpu:latest
    depends_on:
      - cpu-build
    container_name: python_sub
    volumes:
      - .:/src:ro
      - /etc/timezone:/etc/timezone:ro
    command: python3 -u scripts/pubsub/python_sub.py
    stop_signal: SIGTERM
    network_mode: host
    ipc: host
    pid: host
    profiles: [ "pubsub" ]
  ##### test yolo subsystem ############################################################################################
  yolo-cpu-torch-test:
    image: minimal-cpu-torch:latest
    depends_on:
      - cpu-torch-build
    container_name: yolo-cpu-torch-test
    volumes:
      - .:/src:ro
      - /etc/timezone:/etc/timezone:ro
    command: sh -c "mkdir -p "/build" && cd "/build" && cmake -DCMAKE_BUILD_TYPE=Release /src && cmake --build . --target yolo_test -j 8 && src/yolo/yolo_test"
    stop_signal: SIGTERM
    network_mode: host
    ipc: host
    pid: host
    profiles: [ "yolo-cpu-torch-test" ]
  ##### run yolo detector ##############################################################################################
  camera_simulator:
    image: minimal-cpu:latest
    depends_on:
      - cpu-build
    container_name: camera_simulator
    volumes:
      - .:/src:ro
      - /etc/timezone:/etc/timezone:ro
    command: sh -c "mkdir -p "/build" && cd "/build" && cmake -DCMAKE_BUILD_TYPE=Release /src && cmake --build . --target camera_simulator_flatbuffers -j 4 && src/camera_simulator/camera_simulator_flatbuffers"
    stop_signal: SIGTERM
    network_mode: host
    ipc: host
    pid: host
    profiles: [ "yolo-cuda-torch", "yolo-rocm-torch", "yolo-cpu-torch" ]
  yolo-cuda-torch:
    image: minimal-cuda-torch:latest
    depends_on:
      - cuda-torch-build
    container_name: yolo-cuda-torch
    volumes:
      - .:/src:ro
      - /etc/timezone:/etc/timezone:ro
    command: sh -c "mkdir -p "/build" && cd "/build" && cmake -DCMAKE_BUILD_TYPE=Release /src && cmake --build . --target yolo -j 8 && src/yolo/yolo"
    stop_signal: SIGTERM
    network_mode: host
    ipc: host
    pid: host
    profiles: [ "yolo-cuda-torch" ]
  yolo-rocm-torch:
    image: minimal-rocm-torch:latest
    depends_on:
      - rocm-torch-build
    container_name: yolo-rocm-torch
    volumes:
      - .:/src:ro
      - /etc/timezone:/etc/timezone:ro
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp:unconfined
    group_add:
      - video
    command: sh -c "mkdir -p "/build" && cd "/build" && cmake -DCMAKE_BUILD_TYPE=Release /src && cmake --build . --target yolo -j 8 && src/yolo/yolo"
    stop_signal: SIGTERM
    network_mode: host
    ipc: host
    pid: host
    profiles: [ "yolo-rocm-torch" ]
  yolo-cpu-torch:
    image: minimal-cpu-torch:latest
    depends_on:
      - cpu-torch-build
    container_name: yolo-cpu-torch
    volumes:
      - .:/src:ro
      - /etc/timezone:/etc/timezone:ro
    command: sh -c "mkdir -p "/build" && cd "/build" && cmake -DCMAKE_BUILD_TYPE=Release /src && cmake --build . --target yolo -j 8 && src/yolo/yolo"
    stop_signal: SIGTERM
    network_mode: host
    ipc: host
    pid: host
    profiles: [ "yolo-cpu-torch" ]
  ##### run coordinate transform #######################################################################################
  image_to_world:
    image: minimal-cpu:latest
    depends_on:
      - cpu-build
    container_name: image_to_world
    volumes:
      - .:/src:ro
      - /etc/timezone:/etc/timezone:ro
    command: sh -c "mkdir -p "/build" && cd "/build" && cmake -DCMAKE_BUILD_TYPE=Release /src && cmake --build . --target image_to_world -j 4 && src/coordinate_transformation/image_to_world"
    stop_signal: SIGTERM
    network_mode: host
    ipc: host
    pid: host
    profiles: [ "yolo-cuda-torch", "yolo-rocm-torch", "yolo-cpu-torch" ]