services:
  ##### build images (cpu, cuda, rocm) #################################################################################
  cpu-build:
    build:
      context: .
      dockerfile: Dockerfile
      target: image
      args:
        src: cpu
    image: minimal_cpu
    profiles: [ "cpu", "pubsub", "yolo_cuda", "yolo_rocm", "yolo_cpu" ]
  cuda-build:
    build:
      context: .
      dockerfile: Dockerfile
      target: image
      args:
        src: cuda
    image: minimal_cuda
    profiles: [ "cuda", "yolo_cuda" ]
  rocm-build:
    build:
      context: .
      dockerfile: Dockerfile
      target: image
      args:
        src: rocm
    image: minimal_rocm
    profiles: [ "rocm", "yolo_rocm" ]
  ##### run pubsub examples (uses cpu version) #########################################################################
  sub:
    image: minimal_cpu:latest
    depends_on:
      - cpu-build
    container_name: sub
    volumes:
      - .:/src:ro
      - /etc/timezone:/etc/timezone:ro
    command: sh -c "mkdir -p "/build" && cd "/build" && cmake -DCMAKE_BUILD_TYPE=Release /src && cmake --build . --target sub  && src/pubsub/sub"
    stop_signal: SIGTERM
    network_mode: host
    ipc: host
    pid: host
    profiles: [ "pubsub" ]
  pub:
    image: minimal_cpu:latest
    depends_on:
      - cpu-build
    container_name: pub
    volumes:
      - .:/src:ro
      - /etc/timezone:/etc/timezone:ro
    command: sh -c "mkdir -p "/build" && cd "/build" && cmake -DCMAKE_BUILD_TYPE=Release /src && cmake --build . --target pub  && src/pubsub/pub"
    stop_signal: SIGTERM
    network_mode: host
    ipc: host
    pid: host
    profiles: [ "pubsub" ]
  python_sub:
    image: minimal_cpu:latest
    depends_on:
      - cpu-build
    container_name: python_sub
    volumes:
      - .:/src:ro
      - /etc/timezone:/etc/timezone:ro
    command: python3 -u scripts/pubsub/python_sub.py
    stop_signal: SIGTERM
    network_mode: host
    ipc: host
    pid: host
    profiles: [ "pubsub" ]
  ##### run yolo detector ##############################################################################################
  camera_simulator:
    image: minimal_cpu:latest
    depends_on:
      - cpu-build
    container_name: camera_simulator
    volumes:
      - .:/src:ro
      - /etc/timezone:/etc/timezone:ro
    command: sh -c "mkdir -p "/build" && cd "/build" && cmake -DCMAKE_BUILD_TYPE=Release /src && cmake --build . --target camera_simulator_flatbuffers -j 4 && src/camera_simulator/camera_simulator_flatbuffers"
    stop_signal: SIGTERM
    network_mode: host
    ipc: host
    pid: host
    profiles: [ "yolo_cuda", "yolo_rocm", "yolo_cpu" ]
  yolo_cuda:
    image: minimal_cuda:latest
    depends_on:
      - cuda-build
    container_name: yolo_cuda
    volumes:
      - .:/src:ro
      - /etc/timezone:/etc/timezone:ro
    command: sh -c "mkdir -p "/build" && cd "/build" && cmake -DCMAKE_BUILD_TYPE=Release /src && cmake --build . --target yolo -j 8 && src/yolo/yolo"
    stop_signal: SIGTERM
    network_mode: host
    ipc: host
    pid: host
    profiles: [ "yolo_cuda" ]
  yolo_rocm:
    image: minimal_rocm:latest
    depends_on:
      - rocm-build
    container_name: yolo_rocm
    volumes:
      - .:/src:ro
      - /etc/timezone:/etc/timezone:ro
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp:unconfined
    group_add:
      - video
    command: sh -c "mkdir -p "/build" && cd "/build" && cmake -DCMAKE_BUILD_TYPE=Release /src && cmake --build . --target yolo -j 8 && src/yolo/yolo"
    stop_signal: SIGTERM
    network_mode: host
    ipc: host
    pid: host
    profiles: [ "yolo_rocm" ]
  yolo_cpu:
    image: minimal_cpu:latest
    depends_on:
      - cpu-build
    container_name: yolo_cpu
    volumes:
      - .:/src:ro
      - /etc/timezone:/etc/timezone:ro
    command: sh -c "mkdir -p "/build" && cd "/build" && cmake -DCMAKE_BUILD_TYPE=Release /src && cmake --build . --target yolo -j 8 && src/yolo/yolo"
    stop_signal: SIGTERM
    network_mode: host
    ipc: host
    pid: host
    profiles: [ "yolo_cpu" ]
  ##### run coordinate transform #######################################################################################
  image_to_world:
    image: minimal_cpu:latest
    depends_on:
      - cpu-build
    container_name: image_to_world
    volumes:
      - .:/src:ro
      - /etc/timezone:/etc/timezone:ro
    command: sh -c "mkdir -p "/build" && cd "/build" && cmake -DCMAKE_BUILD_TYPE=Release /src && cmake --build . --target image_to_world -j 4 && src/coordinate_transformation/image_to_world"
    stop_signal: SIGTERM
    network_mode: host
    ipc: host
    pid: host
    profiles: [ "yolo_cuda", "yolo_rocm", "yolo_cpu" ]